[[redirects]]
  from = "https://morezindustrial.net.pe/*"
  to = "https://morezindustrial.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.morezindustrial.net.pe/*"
  to = "https://morezindustrial.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
